### ISSUE TITLE
how to use  agent config ip address?

### ISSUE THREAD

**Issue by haiwan-xm** [MrKampf/proxmoxVE#1]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

hi, tks  this api is great project.
so how to use api agent config vm ip address?

**Comment by MrKampf** [comment]
What do you want? You want get the IP's?

**Comment by haiwan-xm** [comment]
> What do you want? You want get the IP's?

we want    running this confg ip addredd
qm guest exec xxx xxx  have give me a   demo.
tks.  forexample  use cloud-init set ip address same.

**Comment by MrKampf** [comment]
Hi,

i think you mean this? 
https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu/{vmid}/agent/exec

**Comment by haiwan-xm** [comment]
> Hi,
> 
> i think you mean this?
> [https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu/{vmid}/agent/exec](https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/%7Bnode%7D/qemu/%7Bvmid%7D/agent/exec)

yes,  we  just  test  use api  config qemu agent ip .  so wish get guide. tks

**Comment by haiwan-xm** [comment]
> Hi,
> 
> i think you mean this?
> [https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu/{vmid}/agent/exec](https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/%7Bnode%7D/qemu/%7Bvmid%7D/agent/exec)

hi    , have give  me  guide? tks

**Comment by haiwan-xm** [comment]
> Hi,
> 
> i think you mean this?
> [https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu/{vmid}/agent/exec](https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/%7Bnode%7D/qemu/%7Bvmid%7D/agent/exec)

hi , boss. how to write php code running exec ?
