### ISSUE TITLE
help: How i can get all vms names 

### ISSUE THREAD

**Issue by acairon** [MrKampf/proxmoxVE#11]
Hello i want to know how to get only the names of lxc or quemus 

$data = $proxmox->nodes()->node('Debian-104-buster-64-minimal')->lxc()->get();

for example

**Comment by MrKampf** [comment]
This command is right, now you get are array back.

```PHP
foreach($data['data'] as $lxc){
echo $lxc['name'];
}

```

I have not testet this code but in theory it should work exactly the same way, if not please contact me again.
