### ISSUE TITLE
Snapshot Rollbacks & Deletion Not Working

### ISSUE THREAD

**Issue by AnushK-Fro** [MrKampf/proxmoxVE#13]
**Describe the bug**
Trying to use the snapname class does not work (which results in rollback + deletion not working).

**To Reproduce**
1. Create a Proxmox instance
2. Attempt to use snapname

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
Here's what we've tried:
`$this->proxmox($server, $cluster)->qemu()->vmid($server->vmid)->snapshot()->snapname($snapname)->postRollback();`
This appears to not work, as we get `Class \"proxmox\\Api\\nodes\\qemu\\snapshot\\snapname\" not found`.

When moving the `postRollback` function to the snapshot class itself (snapshot.php) and adding parameters for the name, it appears to work fine.

`$this->proxmox($server, $cluster)->qemu()->vmid($server->vmid)->snapshot()->postRollback($snapname);`

We added this function to snapshot.php:
```  
public function postRollback($name){
        return connection::processHttpResponse(connection::postAPI($this->httpClient,$this->apiURL.$name.'/rollback/',$this->cookie));
    }
```

Here's the full code to the project that we're working on:
https://github.com/StratumPanel/Stratum-Panel
Code is in `app/Services/Servers/SnapshotService.php`

**Comment by MrKampf** [comment]
Hi,

what version do you use?
The currently 3.7?
In the new version I have added new architecture and better performance.


Then you have to change something:
`
$pve->nodes()->node('example')->qemu()->vmId(1)->snapshot()->snapname('example')->rollback()->post();
`

**Comment by ericwang401** [comment]
> Hi,
> 
> what version do you use? The currently 3.7? In the new version I have added new architecture and better performance.
> 
> Then you have to change something: `$pve->nodes()->node('example')->qemu()->vmId(1)->snapshot()->snapname('example')->rollback()->post();`

Hey, this isn't related to this issue, but it seems kind of redundant/verbose to add `rollback()` and then `post()`

It might be better to just do `return (new Rollback($this->getPve(), $this->getPathAdditional())->post()` for the `rollback` method in `snapname.php` so a user would just have to call `$pve->nodes()->node('example')->qemu()->vmId(1)->snapshot()->snapname('example')->rollback()` without the extra `->post()`

**Comment by MrKampf** [comment]
Hey @ericwang401 ,

thanks a lot for your feedback. I will consider/integrate this in the next update, for single functions such as post.
Currently I have built this so to keep it consistent and so for all equally understandable. But of course I can also add a default return to something like this which makes it easier to use.
Thanks a lot!

**Comment by AnushK-Fro** [comment]
> Hi,
> 
> what version do you use? The currently 3.7? In the new version I have added new architecture and better performance.
> 
> Then you have to change something: `$pve->nodes()->node('example')->qemu()->vmId(1)->snapshot()->snapname('example')->rollback()->post();`

We just updated the API to the newest version and now trying to do something like: `$this->proxmox($server, $cluster)->qemu()->vmid($server->vmid)->status()->start()->post();` doesn't seem to work correctly as it seems to do nothing. I also don't get any errors or output :(

I was able to make it fetch the status though, with this:
`return $this->proxmox($server, $cluster)->qemu()->vmid($server->vmid)->status()->current()->get();`

Here's our full project (Stratum-Next branch):
https://github.com/StratumPanel/Stratum-Panel/tree/Stratum-Next

Start function is in the `PowerService` service under `app/Services/Servers`.

By the way, great job on the API so far!

**Comment by MrKampf** [comment]
Thanks for report.

I have fixed the issue. The problem was i have sent a Content-Type in Header and no content was sent, and this wasn't accepted proxmox in api.

When you want debug, the error you can add behind the authType, true and then you get debug report.

`$proxmox = new PVE('example','dev', 'password',8006, 'pve', true);`

The last true activate the debug mode. 

Thank you for your praise

Thank you for helping me to improve this library and find errors that I can't always find right away.

**Comment by MrKampf** [comment]
The new version is 4.0

**Comment by AnushK-Fro** [comment]
Hey, when I turn on debug mode I get this issue:
{message: "curl_setopt_array(): Cannot represent a stream of type Output as a STDIO FILE*",…}
exception: "ErrorException"
file: "C:\\xampp\\htdocs\\Stratum-Next\\vendor\\guzzlehttp\\guzzle\\src\\Handler\\CurlFactory.php"
line: 70
message: "curl_setopt_array(): Cannot represent a stream of type Output as a STDIO FILE*"
trace: [{function: "handleError", class: "Illuminate\Foundation\Bootstrap\HandleExceptions", type: "->"},…]

**Comment by MrKampf** [comment]
Hi,

the error seems to be caused by the library Guzzehttp. I suspect the Guzzlehttp debug / or that CURL can not debug this, so the type "STDIO FILE". This is what I get from the error message. Otherwise write a thread at https://github.com/guzzle/guzzle they might be able to help you there.
