### ISSUE TITLE
DELETE qemu not working

### ISSUE THREAD

**Issue by SpigotFehlerYT** [MrKampf/proxmoxVE#14]
If i use `$proxmox->nodes()->node('ix-ds-01')->qemu()->vmId($server_id)->delete();` it wont work error:
<html>
<body>

* Closing connection 1
--
  | Server error: `DELETE https://****:8006/api2/json/nodes/ix-ds-01/qemu/215/` resulted in a `501 Unexpected content for method 'DELETE'` response

</body>
</html>

**Comment by MrKampf** [comment]
Hi @SpigotFehlerYT ,

thanks for report. I have fixed this issue, now. Version 0.3.9

Best regrades
MrKampf
