### ISSUE TITLE
Create new release for latest pull request #15

### ISSUE THREAD

**Issue by ericwang401** [MrKampf/proxmoxVE#16]
**Is your feature request related to a problem? Please describe.**
It is related to fix described in https://github.com/MrKampf/proxmoxVE/pull/15

**Describe the solution you'd like**
Is it possible if you can create a new release for this pull request?

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by MrKampf** [comment]
Done

**Comment by MrKampf** [comment]
Done
