### ISSUE TITLE
Supply parameters to GET requests

### ISSUE THREAD

**Issue by sriccio** [MrKampf/proxmoxVE#20]
Hello,

First, thank you for the lib. Look very nice.

I would like to ask if there is a way to specify parameters for GET requests.

For example, the `/cluster/resources` GET method allows a `type` parameter to be passed to limit the results to one kind of object.
https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/resources

The parameters are query parameters, I would imagine there is a way to add them to the Guzzzle get call if they are passed to get function ?.

Something like:

```
$proxmox->cluster->resources->get(['type' => 'vm']);
```

Does it sound reasonable or maybe there is a better way to handle this ?

Kind regards.

**Comment by MrKampf** [comment]
Sorry for my many delay.

One way is to add every optional or required parameter in every function manual.
