### ISSUE TITLE
Storage content error

### ISSUE THREAD

**Issue by Maverick50s** [MrKampf/proxmoxVE#30]
I'm having this request `json_encode($pveconn->nodes()->node($nodename)->storage()->storageId("local")->content()->get(["content"=>"vztmpl"]));` and it's resulting into `Uncaught Error: Call to undefined method Proxmox\\Api\\Nodes\\Node\\Storage::storageId()`.
I'm pretty sure I've got the request right, I've also tried every single other combination that may work but no luck.

**Comment by MrKampf** [comment]
Fixed in version v0.4.3
