### ISSUE TITLE
setCSRFPreventionToken(): Argument #1 ($CSRFPreventionToken) must be of type string, null given

### ISSUE THREAD

**Issue by Mecanik** [MrKampf/proxmoxVE#36]
**Describe the bug**
This bug happens when the login() function at Proxmox/Helper/Api.php(168) cannot login to the host. 

**To Reproduce**
Simulate a failed login so that getCSRFToken() returns similar response:

`cURL error 7: Failed to connect to ...... port 8006: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://......:8006/api2/json/access/ticket`

**Expected behavior**
login() function should return a result and inside it $requestResult should be checked in case of any errors, at the moment the exception in getCSRFToken() is handled and thus returning null for no reason. Later setCSRFPreventionToken() is called with null value and thus throwing an unhandled exception.

**Screenshots**
Sorry, I cannot provide this.

**Desktop (please complete the following information):**
N/A
   
**Server (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by aleksandrvolk** [comment]
who can solve the problem? in local openserver the problem is not observed. In web hosting mistake Backend fatal error: PHP Fatal error:  Uncaught TypeError: Proxmox\\PVE::setCSRFPreventionToken(): Argument #1 ($CSRFPreventionToken) must be of type string, null given, called in
