### ISSUE TITLE
POST returns "HTTP/1.1 401 Permission denied - invalid csrf token"

### ISSUE THREAD

**Issue by Shade634** [MrKampf/proxmoxVE#4]
**Describe the bug**
I dont seem to be able to POST anything, i can get results trough GET.
The error i keep receiving is: "HTTP/1.1 401 Permission denied - invalid csrf token"

I have been trying to search for a solution but i havent found one yet, nor an option that passes the "csrftoken" in the header as mentioned in many solutions: https://forum.proxmox.com/threads/connection-problem-novnc-api.40751/

**To Reproduce**
$proxmox =  new pve($credentials);

$response = $proxmox->nodes()->node($node)->qemu()->vmid($id)->status()->postStart(['node' => $node, 'vmid' => $id]);

**Expected behavior**
A VM that has been started

**Comment by MrKampf** [comment]
Hi Shade634,

thank you for the report. I have found the Problem, in the next hour i load a bugfix up. 
Many thanks for support my library for proxmox :-)

Regrade 
MrKampf

**Comment by MrKampf** [comment]
So update is published. 
Many thanks again :-)

**Comment by Shade634** [comment]
I get a "Object of class GuzzleHttp\Client could not be converted to string" Error now, also on the GET requests.

vendor/mrkampf/proxmox-ve/src/proxmox/pve.php :: getCSRFPreventionToken (line 49)
vendor/mrkampf/proxmox-ve/src/proxmox/pve.php :: refreshCSRFToket (line 263)
vendor/mrkampf/proxmox-ve/src/proxmox/pve.php :: getCSRFToken (line 75)
vendor/mrkampf/proxmox-ve/src/proxmox/Helper/connection.php (line 49)

When i do: 
`new pve($credentials)`

Did i do something wrong?

**Comment by MrKampf** [comment]
Many sorry, i have released the new architecture from this git.
I fixed it.

**Comment by Shade634** [comment]
No worries, i just pulled:

`Package operations: 0 installs, 1 update, 0 removals`
`  - Updating mrkampf/proxmox-ve (0.2.2 => 0.2.6): Downloading (100%)  `

Now it throws me a "Can't login with this data." on 
`new pve($credentials);`
While these credentials did work before?

in vendor/mrkampf/proxmox-ve/src/proxmox/pve.php -> setLoginTokens (line 50)
in vendor/mrkampf/proxmox-ve/src/proxmox/pve.php (line 61)

But if i var_dump($json) it results in:

`array(1) { ["data"]=> array(5) { ["CSRFPreventionToken"] `

**Comment by MrKampf** [comment]
Hi,

i have test this by me and i can login and become no error. Have you right data? Can you send my the code?

**Comment by MrKampf** [comment]
> Hi,
> 
> i have test this by me and i can login and become no error. Have you right data? Can you send my the code?

i mean your code

**Comment by Shade634** [comment]
`$credentials = [`
`           'hostname' => $proxmoxConfig->getDomain(), // ipadres without protocol`
        `    'username' => $proxmoxConfig->getUser(), // username string`
           ` 'password' => $proxmoxConfig->getPassword(true), // password string`
         `   'authType' => 'pam', // string`
         `   'port' => $proxmoxConfig->getPort(), 'string of 4 numbers'`
`        ];`

  `      return new pve($credentials);`

**Comment by Shade634** [comment]
```
  | array(1) {
  | ["data"]=>
  | array(5) {
  | ["CSRFPreventionToken"]=>
  | string(52) "5F1B2D1F:string"
  | ["clustername"]=>
  | string(10) "devcluster"
  | ["ticket"]=>
  | string(367) "PVE:root@pam:5F1B2D1F:looooongStringWithSlashesAnd=="
  | ["username"]=>
  | string(8) "root@pam"
  | ["cap"]=>
  | array(5) {
  | ["dc"]=>
  | array(1) {
  | ["Sys.Audit"]=>
  | int(1)
  | }
  | ["nodes"]=>
  | array(6) {
  | ["Sys.Console"]=>
  | int(1)
  | ["Sys.Syslog"]=>
  | int(1)
  | ["Sys.PowerMgmt"]=>
  | int(1)
  | ["Permissions.Modify"]=>
  | int(1)
  | ["Sys.Audit"]=>
  | int(1)
  | ["Sys.Modify"]=>
  | int(1)
  | }
  | ["vms"]=>
  | array(18) {
  | ["VM.Snapshot.Rollback"]=>
  | int(1)
  | ["VM.Monitor"]=>
  | int(1)
  | ["VM.Config.Network"]=>
  | int(1)
  | ["VM.Config.Options"]=>
  | int(1)
  | ["VM.Config.CPU"]=>
  | int(1)
  | ["VM.Snapshot"]=>
  | int(1)
  | ["Permissions.Modify"]=>
  | int(1)
  | ["VM.PowerMgmt"]=>
  | int(1)
  | ["VM.Config.CDROM"]=>
  | int(1)
  | ["VM.Config.HWType"]=>
  | int(1)
  | ["VM.Console"]=>
  | int(1)
  | ["VM.Config.Disk"]=>
  | int(1)
  | ["VM.Allocate"]=>
  | int(1)
  | ["VM.Audit"]=>
  | int(1)
  | ["VM.Migrate"]=>
  | int(1)
  | ["VM.Clone"]=>
  | int(1)
  | ["VM.Config.Memory"]=>
  | int(1)
  | ["VM.Backup"]=>
  | int(1)
  | }
  | ["storage"]=>
  | array(5) {
  | ["Datastore.Allocate"]=>
  | int(1)
  | ["Datastore.AllocateTemplate"]=>
  | int(1)
  | ["Permissions.Modify"]=>
  | int(1)
  | ["Datastore.Audit"]=>
  | int(1)
  | ["Datastore.AllocateSpace"]=>
  | int(1)
  | }
  | ["access"]=>
  | array(3) {
  | ["Permissions.Modify"]=>
  | int(1)
  | ["Group.Allocate"]=>
  | int(1)
  | ["User.Modify"]=>
  | int(1)
  | }
  | }
  | }
  | }


```

**Comment by Shade634** [comment]
> > Hi,
> > i have test this by me and i can login and become no error. Have you right data? Can you send my the code?
> 
> i mean your code

placed the code and the returned $json, but i still get the "Can't login with this data." while i could get data with this credentials on GET requests before the initial fix

**Comment by Shade634** [comment]
Tho it does not make much sense to me at the moment either.

**Comment by Shade634** [comment]
I will be on vacation for 2 weeks now, i will look deeper into it later.

**Comment by Shade634** [comment]
I have traced the issue, it seems that the 
` private function setLoginTokens($json){ `
is called twice, first with an array, then with a value "NULL" on the second call

**Comment by Shade634** [comment]
` string(13) "type of $json" `
` string(5) "array" `
` string(13) "type of $json" `
` string(4) "NULL" `
` string(6) "call 2" `
` string(4) "NULL" `

when i try to debug the setLoginTokens this way:
`private function setLoginTokens($json){`
`        var_dump('type of $json');`
`        var_dump(gettype($json));`
`        if(!is_array($json)){ //Is $json are array`
`            var_dump('call 2');`
`            var_dump(gettype($json));`
`            throw new AuthenticationException('Can\'t login with this data.');`
`        }`

**Comment by Shade634** [comment]
the `private static function refreshCSRFToket(){` returns null for me which causes this issue it seems

**Comment by Shade634** [comment]
I found the issue, its caused by a foreach loop on my end.

**Comment by MrKampf** [comment]
Good, i have searched a error on my code and i haven't found. But it's good you have found the error. 
Thanks for support this project :-)
