### ISSUE TITLE
Get iso's from storage

### ISSUE THREAD

**Issue by Shade634** [MrKampf/proxmoxVE#6]
I am trying to list the iso's from a storage to install on a Qemu machine however i cannot find the following API command within this library: https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/storage/{storage}/content 

Is there currently to list available iso's (ubuntu, debian etc.)?

**Comment by MrKampf** [comment]
Solved
https://github.com/MrKampf/proxmoxVE/releases/tag/v0.2.9
