### ISSUE TITLE
/api2/json/nodes/{node}/storage

### ISSUE THREAD

**Issue by eliasmagn** [MrKampf/proxmoxVE#7]
Nice work so far!

Is your feature request related to a problem? Please describe. 
Is, 
/api2/json/nodes/{node}/storage
not implemented?
If it is where can i find it?

Describe the solution you'd like 
Implement it ;-)

Additional context
If not i would request that feature, since it is in the api, should be here as well or am i wrong?
Best regards eliasmagn

**Comment by eliasmagn** [comment]
I am working on it already, and i am happy to contribute to that project.
I am quite new to contribute, so please tell me if i do smthing wrong regarding copyright, since i follow your codestyle exactly.
https://github.com/eliasmagn/proxmoxVE/blob/nodestorage/src/proxmox/Api/nodes/node/storage.php

**Comment by MrKampf** [comment]
All fine, when I have the time in next year I integrate this features and all the new Proxmox features. Thanks for support this library!

**Comment by MrKampf** [comment]
https://github.com/MrKampf/proxmoxVE/releases/tag/v0.2.9
https://github.com/MrKampf/proxmoxVE/commit/46ed77280e48ae0349cd2a91163603a78da7462a

Now integrated, thanks for the first code lines!

Many thanks for your support!
@eliasmagn
