### ISSUE TITLE
Include extended guide about how to use basic functions

### ISSUE THREAD

**Issue by okynos** [MrKampf/proxmoxVE#8]
Hello @MrKampf,

First of all, I have to say that this repository is a piece of art! it works like a charm and it's super easy to use (Object notation).

I have a little request/improvement about the way to introduce new users to this repository. I'm currently managing a home lab with Proxmox and I built a simple web for my friends (a little background).

Being short, I started to use this plugin and I noticed that It's hard to understand at least for me.
For example, what does the $param array means? This call works but I don't understand why.
`$proxmox->nodes()->node('mynode')->lxc()->vmid('XXX')->status()->postStart(array())`

Finally, I want to say that I would like to open a pull request when I fully understand the code to help newcomers to introduce this plugin. Thanks for reading me.

Regards.

**Comment by MrKampf** [comment]
Hi @okynos ,

in the $params you write an array with all parameters that the api needs. 

Example start

```php
$params = [
'debug' => 1,
'skiplock' => 1,
];

$proxmox->nodes()->node('mynode')->lxc()->vmid('XXX')->status()->postStart($params)
```

https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/lxc/{vmid}/status/start
